services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    environment:
      - ENV=development
    command: go run main.go  # Modo de desenvolvimento

  db:
    image: postgres:alpine
    environment:
      POSTGRES_USER: tgame
      POSTGRES_PASSWORD: tgame
      POSTGRES_DB: tgame
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

volumes:
  db_data:
